from .global_model.model_functions.multivariate_model import MultivariateModel as MultivariateModelGlobal
from .regional_model.model_functions.multivariate_model import MultivariateModel as MultivariateModelRegional
